---
format: html
pagetitle: Home
---

# Math Review for MDS

Welcome to MDS! We hope this math review will help you refresh your memory on core concepts from calculus and linear algebra, and prepare you to apply these concepts in the context of data science and machine learning.

There are several free and excellent resources available on the internet for learning calculus and linear algebra. We did not attempt to add a new item to this list, and this site does not offer a standalone course on mathematics for data science. Our objective instead was to curate a list of pre-existing (and usually open-source) materials. We link to them through the modules listed in the navigation panel, and provide exercises and short accompanying text. The "Reference Material" section contains a compelete list of references.

If you find this website useful, we encourage you to return to it throughout the program as needed to reinforce your understanding.

### How to use this site

Students come to MDS with a variety of mathematical backgrounds. You may find yourself very familiar with some material on this site, but lacking that familiarity elsewhere. Feel free to attempt the modules in any order, based on your background and interest. If you have taken coursework on (say) single- and multi-variable calculus but not linear algebra, you could quickly review exercises from Modules 1 and 2 before proceeding onto Module 3. Then, you could spend some time watching the linked videos on vector spaces and matrix multiplication, before finishing by attempting exercises from Module 3. If you have never taken a course on multivariable calculus you may prefer instead to spend more time on Module 2, and additionally use the list of reference materials to find a textbook to work through.

The exercises for each module contain a mix of multiple-choice and open-ended questions. Some questions are meant to be short and easy, while others are designed to be challenging and take some time and effort to solve. It is ok if a few of the questions prove too difficult on your first attempt!

### Your First Task

Click the arrow at the bottom-right of this page to move on to the next section.