project:
  type: website
  title: "Math Review for MDS"
  # Setting the execution dir allows us to use `data/`
  # instead of relative paths in regular code cells
  execute-dir: project
  # `render` executes and renders modules, slides, and exercises into `_site`
  render:
    - modules/**/*.qmd
    - modules/index.qmd
  # `resources` copies files into `_site` without execution
  resources:
    - styles.scss
    - src/utils.py
    - data
    - static

# Setting the pyodide resources allows live code cells to see files
# previously copied into `_site`
# by copying them to the virtual file system used by live coding
pyodide:
  resources:
    - src/utils.py
    - data

website:
  page-navigation: true
  bread-crumbs: false
  sidebar:
    collapse-level: 1
    logo: static/mds-hex-sticker.png
    search: true
    style: 'docked'
    background: 'primary'
    contents:
      - section: "**M0. Welcome**"
        contents:
          - text: '0. Welcome!'
            href: modules/index.qmd
          - href: modules/module0/module0-01-reference_material.qmd
      - section: "**M1. Functions of a Single Variable**"
        contents:
          - href: modules/module1/module1-01-understanding-the-derivative.qmd
          - text: '&nbsp;&nbsp; 1.1. Exercises'
            href: modules/module1/module1-ex1_1.qmd
          - href: modules/module1/module1-02-derivatives-common-functions.qmd
          - text: '&nbsp;&nbsp; 1.2. Exercises'
            href: modules/module1/module1-ex1_2.qmd
          - href: modules/module1/module1-03-chain-rule.qmd
          - text: '&nbsp;&nbsp; 1.3. Exercises'
            href: modules/module1/module1-ex1_3.qmd
          - href: modules/module1/module1-04-max-min.qmd
      - section: "**M2. Functions of Several Variables**"
        contents:
          - href: modules/module2/module2-01-several-variables.qmd
          - text: '&nbsp;&nbsp; 2.1. Exercises'
            href: modules/module2/module2-ex2_1.qmd
          - href: modules/module2/module2-02-opt-conv.qmd
          - text: '&nbsp;&nbsp; 2.2. Exercises'
            href: modules/module2/module2-ex2_2.qmd
      - section: "**M3. Matrices and Vectors**"
        contents:
          - href: modules/module3/module3-01-vecs.qmd
          - text: '&nbsp;&nbsp; 3.1. Exercises'
            href: modules/module3/module3-ex3_1.qmd
          - href: modules/module3/module3-02-mats.qmd
          - text: '&nbsp;&nbsp; 3.2. Exercises'
            href: modules/module3/module3-ex3_2.qmd
          - text: '&nbsp;&nbsp; 3.3 A Bonus Question'
            href: modules/module3/module3-ex3_3.qmd
      - section: "**Feedback**"
        contents:
          - href: modules/last.qmd
      #- section: "**M4. More with Linear Algebra**"
      #  contents:
      #    - href: modules/module4/module4-01-building_a_picture.qmd
      #    - text: '&nbsp;&nbsp; 4.1. Exercises'
      #      href: modules/module4/module1-ex4_1.qmd

# Since we are declaring options for two formats here (html and revealjs)
# each qmd file needs to include a yaml block including which format to use for that file.
# https://github.com/quarto-dev/quarto-cli/issues/4583
format:
  html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#283791'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  live-html:
    callout-icon: false
    theme: [united, styles.scss]
    linkcolor: '#283791'
    highlight-style: atom-one
    grid:
      sidebar-width: 350px
      margin-width: 800px
  revealjs:
    theme: styles.scss
    width: 100%
    monofont: Ubuntu Mono
    mainfont: Ubuntu
    font-size: 0.5em
    monobackgroundcolor: '#F1F3F5'
    highlight-style: atom-one
    # tango atom-one  nord
    transition: slide
    controls-layout: bottom-right
    show-notes: true
    slide-number: true
    code-line-numbers: false
    code-copy: true
    progress: false
    history: false
    menu: false
    execute:
      echo: true
