---
format:
  html:
    page-layout: full
---

# 2. What is a Matrix for?

::: {.panel-tabset .nav-pills}

## Intro

#### Multiplying a Matrix and a Vector

A matrix is a square array of numbers, i.e. a table containing individual entries arranged into rows and columns. A matrix with $m$ rows and $n$ columns would have $m\cdot n$ total entries, $n$ in each row and $m$ in each column. For example, if $m=2$ and $n=3$ we may have the matrix
$$
\begin{bmatrix}a&b&c\\d&e&f\end{bmatrix} \quad\text{where}\quad a,b,c,d,e,f \text{ are real numbers.}
$$
If we have an $m\times n$ matrix $A$ and an $n$-dimensional vector $v$, then there is a rule that allows us to produce the *matrix-vector product* $A\cdot v$. The result of this product is also a vector. Its first entry is given by the dot-product of the first row of $A$ with the vector $v$, the second entry by the dot-product of the second row of $A$ with the vector $v$, and so on. In the case $m=2,\, n=3$ this would look something like:
$$
\begin{bmatrix}a&b&c\\d&e&f\end{bmatrix}\cdot \begin{bmatrix}x\\y\\z\end{bmatrix} = \begin{bmatrix}ax+by+cz\\dx+ey+fz\end{bmatrix}.
$$

Notice immediately that the number of columns of $A$ must agree with the dimension (no. of entries) of the vector $v$--- otherwise the rule cannot be applied. Note also that just because $Av$ can be computed doesn't mean the product $vA$ is even defined (and it certainly doesn't have to equal $Av$ if it is).

#### Matrices as Maps Between Vector Spaces

In the previous section, we have seen that multiplying an $m\times n$ matrix $A$ by an $n$-dimensional vector $v$ in the order $A\cdot v$ produces an $m$-dimensional vector. Thus for each matrix $A$ we have an associated function $f_A$ given by this "left-multiplication":
$$
f_A(w) = A\cdot w \quad \text{for any $n$-dimensional vector } w.
$$
This is a function from $n$-dimensional space to $m$-dimensional space. As it turns out, this function is "linear", which simply means that for $n$-dimensional vectors $v$ and $w$ and constants $a$ and $b$ we have
$$
f_A(av+bw) = af_A(v) + bf_A(w).
$$
Such functions map flat surfaces to flat surfaces. In the special case where $m=n$, we get a function from $n$-dimensional space to itself. Some common examples include stretching or shrinking by a constant factor in a given direction, as well as rotations and reflections. These are all examples of linear transformations, and they can all be represented as left multiplication by some well-chosen matrix.

#### Matrices of Data

We have seen that it is common to interpret data points as vectors in some suitable high-dimensional space--- our entire dataset then becomes a *list* of vectors. Writing each vector as an independent row a square array, we get a matrix of data. If the data points are $n$-dimensional, and we have $m$ total points, we end up with an $m\times n$ matrix representing our dataset.

It turns out that matrices are central objects in linear algebra, and they will appear in many guises throughout your coursework at MDS. The theory of matrices--- in particular the study of their eigenvalues, singular values and various decompositions--- has proven extremely fruitful in data science and machine learning.



## Video 1

<iframe
    class="video"
    src="https://www.youtube.com/embed/kYB8IZa5AuE" 
    title="Linear Transformations and matrices"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen
></iframe>

## Video 2

<iframe
    class="video"
    src="https://www.youtube.com/embed/uQhTuRlWMxw" 
    title="Inverse matrices, column space and null space"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen
></iframe>

## Video 3

<iframe
    class="video"
    src="https://www.youtube.com/embed/jY-Mu6XQ3NU" 
    title="The Four Fundamental Subspaces and Least Squares"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen
></iframe>

Alternatively, if you want a slightly longer lecture recording on the same topic by the same speaker, you can see this video:

<iframe
    class="video"
    src="https://www.youtube.com/embed/nHlE7EgJFds" 
    title="The Four Fundamental Subspaces"
    frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen
></iframe>


:::
