---
format: html
---

<script src='../../src/quiz.js'></script>  

# 3.1. Exercises

## Vectors

<div id='vecsum'></div>
<script>
generateQuiz(
    'vecsum',
    'A linear combination of vectors',
    `Let v<sub>1</sub> = [1,1,0], v<sub>2</sub> =[1,0,0]. Calculate the sum v<sub>1</sub> + v<sub>2</sub>.`,
    {
        '[0,0,0]': 'Not quite.',
        '[1,1,1]': 'Try again',
        '[0,1,0]': 'Try again',
        '[2,1,0]': '',
        '[0, 0, 2]': 'Not quite'
    },
    '[2,1,0]'
);
</script>

<div id='subsp'></div>
<script>
generateQuiz( 
    'subsp',
    'Subspace spanned by two vectors',
    `Is the vector [0,1,2] contained in the subspace spanned by the two vectors v<sub>1</sub> = [1,1,0] and v<sub>2</sub> =[1,0,0]?`,
    {
        'Yes': 'Try again--- what must be the last entry in any sum of v<sub>1</sub> and v<sub>2</sub>',
        'No': 'There is no way to get a non-zero value for the third entry in a sum of v<sub>1</sub> and v<sub>2</sub>',
        'Can\'t be sure': 'Try again--- what must be the last entry in any sum of v<sub>1</sub> and v<sub>2</sub>?'
    },
    'No'
);
</script>

<div id='sub2'></div>
<script>
generateQuiz(
    'sub2',
    'Subspace spanned by two vectors',
    `Is the vector [0,0,1] contained in the subspace spanned by the three vectors v<sub>1</sub> = [1,1,0], v<sub>2</sub> =[1,0,0] and v<sub>3</sub> =[0,1,2]?`,
    {
        'Yes': 'These three vectors are linearly independent, so they span the full three-dimensional space. Every vector in the whole space is part of their span!',
        'No': 'Try again! If you are unsure, see the hint below',
        'Can\'t be sure': 'Try again! If you are unsure, see the hint below'
    },
    'Yes'
);
</script>

::: {.callout-note collapse="true"}
## Hint

In the previous question, we should have seen that v<sub>3</sub> is linearly independent from v<sub>1</sub> and v<sub>2</sub>. What does this tell us about the *dimension* of the space spanned by these three vectors? Which vectors in three-dimensional space are part of this span?

:::

<div id='writesum'></div>
<script>
generateQuiz(
    'writesum',
    'Writing a linear sum',
    `Write the vector [0,0,1] as a linear combination of v<sub>1</sub> = [1,1,0], v<sub>2</sub> =[1,0,0] and v<sub>3</sub> =[0,1,2]?`,
    {
        'v<sub>1</sub> - v<sub>2</sub> + v<sub>3</sub>': 'Not quite.',
        '-v<sub>1</sub> + v<sub>2</sub> + v<sub>3</sub>': 'Try again!',
        '0.5v<sub>1</sub> - 0.5v<sub>2</sub> + 0.5v<sub>3</sub>': 'Try again!',
        '-0.5v<sub>1</sub> + 0.5v<sub>2</sub> + 0.5v<sub>3</sub>': '',
        '2v<sub>1</sub> + 2v<sub>2</sub> + 2v<sub>3</sub>': 'Not quite.',
    },
    '-0.5v<sub>1</sub> + 0.5v<sub>2</sub> + 0.5v<sub>3</sub>'
);
</script>

::: {.callout-note collapse="true"}
## Hint

Start with an arbitrary sum av<sub>1</sub>+bv<sub>2</sub>+cv<sub>3</sub> and determine what a, b and c must be in order to get [0,0,1] as the result. You should find yourself needing to solve a system of 3 linear equations.

:::