{
  "hash": "f593feb3790fb953fbb4c25425bd7de6",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nformat: revealjs\ntitle: \"Baselines: Training a Model using Scikit-learn\"\ntitle-slide-attributes:\n  data-notes: |\n\n---\n\n\n\n## Supervised Learning (Reminder)\n\n- Tabular data → Machine learning algorithm → ML model → new examples → predictions\n\n\n![](../../../static/module1/sup-learning.png){fig-alt=\"A caption\" fig-align=\"center\" width=\"80%\"}\n\n\n:::{.notes}\nTo recap what we have seen so far in supervised machine learning we are given some training data. \n\nWe separate our data into features (`X`) and target (`y`), we feed it to our learning algorithm, then the learning algorithm learns some function which we call our machine learning model and we use this to predict the target on unseen test examples. \n:::\n\n---\n\n## Building a simplest machine learning model using sklearn\n\n<br><br>\n\nBaseline model:          \n\n**most frequent baseline**: always predicts the most frequent label in the training set.\n\n\n\n:::{.notes}\nLet’s build a baseline, a simple machine learning algorithm based on simple rules.\n\nWe are going to build a most frequent baseline model which always predicts the most frequently labeled in the training set.\n\nWe make baseline models not to use for prediction purposes, but as a reference point when we are building other more sophisticated models.  \n:::\n\n---\n\n## Data \n\n::: {#e2661519 .cell execution_count=2}\n``` {.python .cell-code}\nclassification_df = pd.read_csv(\"data/quiz2-grade-toy-classification.csv\")\nclassification_df.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ml_experience</th>\n      <th>class_attendance</th>\n      <th>lab1</th>\n      <th>lab2</th>\n      <th>lab3</th>\n      <th>lab4</th>\n      <th>quiz1</th>\n      <th>quiz2</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>1</td>\n      <td>92</td>\n      <td>93</td>\n      <td>84</td>\n      <td>91</td>\n      <td>92</td>\n      <td>A+</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>0</td>\n      <td>94</td>\n      <td>90</td>\n      <td>80</td>\n      <td>83</td>\n      <td>91</td>\n      <td>not A+</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0</td>\n      <td>0</td>\n      <td>78</td>\n      <td>85</td>\n      <td>83</td>\n      <td>80</td>\n      <td>80</td>\n      <td>not A+</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>0</td>\n      <td>1</td>\n      <td>91</td>\n      <td>94</td>\n      <td>92</td>\n      <td>91</td>\n      <td>89</td>\n      <td>A+</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>0</td>\n      <td>1</td>\n      <td>77</td>\n      <td>83</td>\n      <td>90</td>\n      <td>92</td>\n      <td>85</td>\n      <td>A+</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{.notes}\nLet's take our data. \n\nFor this example, we are going to be working with the quiz2 classification data that we have seen previously. \n\nIn this dataset, we have 7 features with our target column being `quiz2` which has 2 possible values; `A+` or `Not A+`. \n:::\n\n---\n\n## 1. Create  𝑋  and  𝑦\n\n𝑋  → Feature vectors <br>\n𝑦  → Target\n\n::: {#f657dd22 .cell execution_count=3}\n``` {.python .cell-code}\nX = classification_df.drop(columns=[\"quiz2\"])\ny = classification_df[\"quiz2\"]\n```\n:::\n\n\n:::{.notes}\nWhenever we build models, there are several important steps involved. \n\nOur first step in building our model is splitting up our tabular data into the features and the target, also known as 𝑋 and 𝑦. \n\n𝑋 is all of our features in our data, which we also call our ***feature table***. <br>\n𝑦 is our target, which is what we are predicting.\n\nFor this problem, all the columns in our dataframe except `quiz2` make up our 𝑋 and the `quiz2` column, which is our target make up our 𝑦. \n:::\n\n---\n\n## 2. Create a classifier object\n\n- `import` the appropriate classifier. \n- Create an object of the classifier. \n\n::: {#158e3133 .cell execution_count=4}\n``` {.python .cell-code}\nfrom sklearn.dummy import DummyClassifier\n\ndummy_clf = DummyClassifier(strategy=\"most_frequent\")\n```\n:::\n\n\n:::{.notes}\nOur next step is creating a model object. \n\nTo make our baseline model, we need to import the necessary library.\n\nWe spoke about the Scikit Learn package in the last slide deck and we are using the same package to build our baseline model. \n\nHere we are importing `DummyClassifier()` which will be used to create our baseline model. \n\nWe specify in the `strategy` argument `most_frequent` which means our model will always predict the most frequent label in the training set. \n\nHere we are naming our model `dummy_clf`.\n:::\n\n---\n\n## 3. Fit the classifier\n\n::: {#a69b4558 .cell execution_count=5}\n``` {.python .cell-code}\ndummy_clf.fit(X, y)\n```\n:::\n\n\n:::{.notes}\nNext, we fit the classifier.\n\nWhen we call fit on our model object, the actual learning happens. In our simple model there is not much to learn and in this case, will only learn what the most frequent label is in our training data. \n:::\n\n---\n\n## 4. Predict the target of given examples\n\nWe can predict the target of examples by calling `predict` on the classifier object. \n\nLet's see what it predicts for a single observation first:<br>\n\n::: {#d20e40d5 .cell execution_count=6}\n``` {.python .cell-code}\nsingle_obs = X.loc[[0]]\nsingle_obs\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ml_experience</th>\n      <th>class_attendance</th>\n      <th>lab1</th>\n      <th>lab2</th>\n      <th>lab3</th>\n      <th>lab4</th>\n      <th>quiz1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>1</td>\n      <td>92</td>\n      <td>93</td>\n      <td>84</td>\n      <td>91</td>\n      <td>92</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n::: {#b48c02f9 .cell execution_count=7}\n``` {.python .cell-code}\ndummy_clf.predict(single_obs)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\narray(['not A+'], dtype='<U6')\n```\n:::\n:::\n\n\n:::{.notes}\n\nOnce we have our learned model, the next thing we can do is predict using it!\n\nFirst, we will predict a single observation. \nWe call our model `dummy_clf` on the object and we get a prediction of `Not A+` for it. \n:::\n\n---\n\n::: {#1d54d4c0 .cell execution_count=8}\n``` {.python .cell-code}\nX\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>ml_experience</th>\n      <th>class_attendance</th>\n      <th>lab1</th>\n      <th>lab2</th>\n      <th>lab3</th>\n      <th>lab4</th>\n      <th>quiz1</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1</td>\n      <td>1</td>\n      <td>92</td>\n      <td>93</td>\n      <td>84</td>\n      <td>91</td>\n      <td>92</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1</td>\n      <td>0</td>\n      <td>94</td>\n      <td>90</td>\n      <td>80</td>\n      <td>83</td>\n      <td>91</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>0</td>\n      <td>0</td>\n      <td>78</td>\n      <td>85</td>\n      <td>83</td>\n      <td>80</td>\n      <td>80</td>\n    </tr>\n    <tr>\n      <th>...</th>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n      <td>...</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>1</td>\n      <td>1</td>\n      <td>91</td>\n      <td>93</td>\n      <td>90</td>\n      <td>88</td>\n      <td>82</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>0</td>\n      <td>1</td>\n      <td>77</td>\n      <td>94</td>\n      <td>87</td>\n      <td>81</td>\n      <td>89</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>1</td>\n      <td>1</td>\n      <td>96</td>\n      <td>92</td>\n      <td>92</td>\n      <td>96</td>\n      <td>87</td>\n    </tr>\n  </tbody>\n</table>\n<p>21 rows × 7 columns</p>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n::: {#4cf7d49c .cell execution_count=9}\n``` {.python .cell-code}\ndummy_clf.predict(X)\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\narray(['not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+', 'not A+'], dtype='<U6')\n```\n:::\n:::\n\n\n:::{.notes}\nWe can also predict on many examples. \n\nHere, we are predicting on all of `X`. \n\nAnd if we see the predictions for all the observations in `X`, the model predicts a value of `not A+` for each one.\n\nThat’s because `Not A+` is the most frequent label in our training set. \n\nWe will talk more about `.fit()` and `.predict()` in the next module.  \n:::\n\n---\n\n## 5. Scoring your model\n\nIn the classification setting, `.score()` gives the accuracy of the model, i.e., proportion of correctly predicted observations. \n\n![](../../../static/module1/predit_total.gif){fig-align=\"center\"}\n\nSometimes you will also see people reporting error, which is usually  1−𝑎𝑐𝑐𝑢𝑟𝑎𝑐𝑦 \n\n![](../../../static/module1/error.gif){fig-align=\"center\"}\n\n::: {#25552199 .cell execution_count=10}\n``` {.python .cell-code}\nprint(\"The accuracy of the model on the training data:\", (round(dummy_clf.score(X, y), 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe accuracy of the model on the training data: 0.524\n```\n:::\n:::\n\n\n<br>\n\n::: {#48ca9926 .cell execution_count=11}\n``` {.python .cell-code}\nprint(\"The error of the model on the training data:\", (round(1 - dummy_clf.score(X, y), 3)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nThe error of the model on the training data: 0.476\n```\n:::\n:::\n\n\n:::{.notes}\nIt's at this point where we can see how well our baseline model predicts the `quiz2` value.  \n\nIn ML models, very often it is not possible to get 100% accuracy.\nHow do we check how well our model is doing?\n\nIn the classification setting, `score()` gives the accuracy of the model, i.e., the proportion of correctly predicted examples.\n\nSometimes we will also see people reporting error, which is usually 1 - accuracy. \n\nWe can see that our model's accuracy on our `quiz2` problem is 0.524. \n\nWe could also say the error is 0.476. \n:::\n\n---\n\n## fit and predict paradigms\n\nThe general pattern when we build ML models using `sklearn`: \n\n1. Creating your 𝑋 and 𝑦 objects \n2. `clf = DummyClassifier()` &rarr; create a model (here we are naming it `clf`)  \n3. `clf.fit(X, y)` &rarr; train the model \n4. `clf.score(X, y)` &rarr; assess the model\n5. `clf.predict(Xnew)` &rarr; predict on some new data using the trained model \n\n:::{.notes}\nTo summarize, here are the steps we follow when building machine learning models using `sklearn`.\n\n1. Create our 𝑋 and 𝑦 objects\n2. Create our model object ( in this case, we created a dummy classifier)\n3. Fit our model\n4. Assess our model\n5. Predict on new examples using this model.\n:::\n\n# Let’s apply what we learned!\n\n",
    "supporting": [
      "module1_13_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}