{
  "hash": "8063e4597fbd27d7291bbfa875360efa",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nformat: revealjs\ntitle: Finding the Nearest Neighbour\ntitle-slide-attributes:\n  data-notes: |\n    Now that we know how to calculate the distance between two points, we are ready to find the most similar examples. \n---\n\n\n\n::: {#ad1b297f .cell execution_count=2}\n``` {.python .cell-code}\ncities_df = pd.read_csv(\"data/canada_usa_cities.csv\")\ntrain_df, test_df = train_test_split(cities_df, test_size=0.2, random_state=123)\ntrain_df.head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>longitude</th>\n      <th>latitude</th>\n      <th>country</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>160</th>\n      <td>-76.4813</td>\n      <td>44.2307</td>\n      <td>Canada</td>\n    </tr>\n    <tr>\n      <th>127</th>\n      <td>-81.2496</td>\n      <td>42.9837</td>\n      <td>Canada</td>\n    </tr>\n    <tr>\n      <th>169</th>\n      <td>-66.0580</td>\n      <td>45.2788</td>\n      <td>Canada</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n\n::: {#c4c51399 .cell execution_count=4}\n``` {.python .cell-code}\nfrom sklearn.metrics.pairwise import euclidean_distances\ndists = euclidean_distances(train_df[[\"latitude\", \"longitude\"]])\ndists\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\narray([[ 0.        ,  4.92866046, ...,  3.13968038,  9.58476504],\n       [ 4.92866046,  0.        , ...,  1.80868018, 14.45684087],\n       ...,\n       [ 3.13968038,  1.80868018, ...,  0.        , 12.70774745],\n       [ 9.58476504, 14.45684087, ..., 12.70774745,  0.        ]], shape=(167, 167))\n```\n:::\n:::\n\n\n<br>\n\n::: {#a0480db0 .cell execution_count=5}\n``` {.python .cell-code}\ndists.shape\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n(167, 167)\n```\n:::\n:::\n\n\n:::{.notes} \nLet's look at the distances from all the cities to all other cities in our training portion of our city's data. \n\nThis is going to be of shape 167 by 167 as this was the number of examples in our training portion.\n\nEach row here gives us the distance of that particular city to all other cities in the training data. \n:::\n\n---\n\n::: {#a49f2e3c .cell execution_count=6}\n``` {.python .cell-code}\npd.DataFrame(dists).loc[:5,:5]\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n      <th>3</th>\n      <th>4</th>\n      <th>5</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>0.000000</td>\n      <td>4.928660</td>\n      <td>10.475863</td>\n      <td>3.402295</td>\n      <td>9.046000</td>\n      <td>44.329135</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>4.928660</td>\n      <td>0.000000</td>\n      <td>15.363990</td>\n      <td>8.326614</td>\n      <td>13.965788</td>\n      <td>39.839439</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>10.475863</td>\n      <td>15.363990</td>\n      <td>0.000000</td>\n      <td>7.195350</td>\n      <td>2.653738</td>\n      <td>54.549042</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>3.402295</td>\n      <td>8.326614</td>\n      <td>7.195350</td>\n      <td>0.000000</td>\n      <td>5.643921</td>\n      <td>47.391337</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>9.046000</td>\n      <td>13.965788</td>\n      <td>2.653738</td>\n      <td>5.643921</td>\n      <td>0.000000</td>\n      <td>52.532333</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>44.329135</td>\n      <td>39.839439</td>\n      <td>54.549042</td>\n      <td>47.391337</td>\n      <td>52.532333</td>\n      <td>0.000000</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n::: {#1755121a .cell execution_count=7}\n``` {.python .cell-code}\nnp.fill_diagonal(dists, np.inf)\npd.DataFrame(dists).loc[:5,:5]\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>0</th>\n      <th>1</th>\n      <th>2</th>\n      <th>3</th>\n      <th>4</th>\n      <th>5</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>inf</td>\n      <td>4.928660</td>\n      <td>10.475863</td>\n      <td>3.402295</td>\n      <td>9.046000</td>\n      <td>44.329135</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>4.928660</td>\n      <td>inf</td>\n      <td>15.363990</td>\n      <td>8.326614</td>\n      <td>13.965788</td>\n      <td>39.839439</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>10.475863</td>\n      <td>15.363990</td>\n      <td>inf</td>\n      <td>7.195350</td>\n      <td>2.653738</td>\n      <td>54.549042</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>3.402295</td>\n      <td>8.326614</td>\n      <td>7.195350</td>\n      <td>inf</td>\n      <td>5.643921</td>\n      <td>47.391337</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>9.046000</td>\n      <td>13.965788</td>\n      <td>2.653738</td>\n      <td>5.643921</td>\n      <td>inf</td>\n      <td>52.532333</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>44.329135</td>\n      <td>39.839439</td>\n      <td>54.549042</td>\n      <td>47.391337</td>\n      <td>52.532333</td>\n      <td>inf</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{.notes} \nNote that we are replacing these diagonal entries by infinity in the matrix.\n\nThe distance of each city to itself is going to be zero. \n\nIf we don't replace 0 with infinity, each city’s most similar city is going to be itself which is not useful. \n:::\n\n---\n\nFeature vector for city 0:\n\n::: {#06f55b49 .cell execution_count=8}\n``` {.python .cell-code}\ntrain_df.iloc[0]\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\nlongitude   -76.4813\nlatitude     44.2307\ncountry       Canada\nName: 160, dtype: object\n```\n:::\n:::\n\n\n<br>\n\nDistances from city 0 to 5 other cities:\n\n::: {#3ad85cc6 .cell execution_count=9}\n``` {.python .cell-code}\ndists[0][:5]\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\narray([        inf,  4.92866046, 10.47586257,  3.40229467,  9.04600003])\n```\n:::\n:::\n\n\n:::{.notes} \nNow let's look at the distance between city 0 and some other cities. \n\nWe can look at city 0 with its respective `longitude` and `latitude` values. \n\nHere, we are printing the distances from city 0 to 5 other cities in the training dataset.\n\nRemember that our goal is to find the closest example. \n\nSo, in our case, we want to find the closest example to city 0. \n\nWe can find the closest city to city 0 by finding the city with the minimum distance. \n:::\n\n---\n\n::: {#608ddc31 .cell execution_count=10}\n``` {.python .cell-code}\ntrain_df.iloc[[0]]\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>longitude</th>\n      <th>latitude</th>\n      <th>country</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>160</th>\n      <td>-76.4813</td>\n      <td>44.2307</td>\n      <td>Canada</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n::: {#9d70b287 .cell execution_count=11}\n``` {.python .cell-code}\nnp.argmin(dists[0])\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\nnp.int64(157)\n```\n:::\n:::\n\n\n<br>\n\n::: {#69a80935 .cell execution_count=12}\n``` {.python .cell-code}\ntrain_df.iloc[[157]]\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>longitude</th>\n      <th>latitude</th>\n      <th>country</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>96</th>\n      <td>-76.3019</td>\n      <td>44.211</td>\n      <td>Canada</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n::: {#16aa3955 .cell execution_count=13}\n``` {.python .cell-code}\ndists[0][157]\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```\nnp.float64(0.18047839205805613)\n```\n:::\n:::\n\n\n:::{.notes} \nSo, we take <a href=\"https://numpy.org/doc/stable/reference/generated/numpy.argmin.html\" target=\"_blank\">`np.argmin`</a> to find the city with the minimum distance from city 0. \n\nThe closest city in our case turned out to be the city with index 157 from our training dataset ( this corresponds to the index 96 from the original dataset before shuffling).\n\nIf we look at the `longitude` and `latitude` values for the city at index 157 (labeled 96), they look pretty close to those of city 0. \n\nSo, in this case, the closest city to city 0 is city 157 and the Euclidean distance between the two cities is 0.184. \n:::\n\n---\n\n## Finding the distances to a query point\n\n::: {#e5fc41a4 .cell execution_count=14}\n``` {.python .cell-code}\nquery_point = [[-80, 25]]\n\ndists = euclidean_distances(train_df[[\"longitude\", \"latitude\"]], query_point)\ndists[0:5]\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\narray([[19.54996348],\n       [18.02706204],\n       [24.60912622],\n       [21.39718237],\n       [25.24111312]])\n```\n:::\n:::\n\n\n<br>\n\nWe can find the city closest to the query point (-80, 25) using:\n\n::: {#2a9d6d18 .cell execution_count=15}\n``` {.python .cell-code}\nnp.argmin(dists)\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\nnp.int64(147)\n```\n:::\n:::\n\n\n<br>\n\nThe distance between the query point and closest city is:\n\n::: {#ddb479ae .cell execution_count=16}\n``` {.python .cell-code}\ndists[np.argmin(dists)].item()\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\n3.8383922936564634\n```\n:::\n:::\n\n\n:::{.notes} \nNext, let’s find the distances to a given query point. \n\nBefore we were calculating the distances between all the cities in our training dataset to all other cities in the same set.\n\nBut what if instead, we are given this new query point which does not occur in our training data.  \n\nSo, suppose we have the query point with a longitude value of -80 and a latitude value of 25.\n\nWe want to find the training example that's most similar to this query point.  \n\nHow can we do that? \n\nFirst, we calculate the distances from a credit point to all examples in our training set.\n\nWe are showing the distances of our query point to the first five cities in our training data. \n\nNext, we find out which city from our training data the query point is closest to.\n\nIt turns out that the city at index 147 is close to our point with the Euclidean distance between the two equal to 3.838.\n:::\n\n---\n\n::: {#4967da82 .cell execution_count=17}\n``` {.python .cell-code}\nfrom sklearn.neighbors import NearestNeighbors\nnn = NearestNeighbors(n_neighbors=1)\nnn.fit(train_df[['longitude', 'latitude']]);\nnn.kneighbors([[-80, 25]])\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n(array([[3.83839229]]), array([[147]]))\n```\n:::\n:::\n\n\n:::{.notes} \nWe use Sklearn's `NearestNeighbors` function to get the closest example and the distance between the query point and the closest example. \n\nFirst, we create our “class” object (we can specify the number of closest neighbours we wish to find), we train on it, and then we can pass our query example to our object to return the closest number of examples along with the distances.\n\nAnd we could also extend it to points in multi-dimensional space.\n\nAll this matches our intuition of \"distance\" in the real world.\n:::\n\n---\n\n::: {#49fb99c3 .cell execution_count=18}\n``` {.python .cell-code}\npokemon_df = pd.read_csv(\"data/pokemon.csv\")\nX = pokemon_df.drop(columns = ['deck_no', 'name','total_bs', 'type', 'legendary'])\ny = pokemon_df[['legendary']]\nX_train, X_test, y_train,  y_test = train_test_split(X, y, test_size=0.2, random_state=123)\n\nX_train.head()\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>attack</th>\n      <th>defense</th>\n      <th>sp_attack</th>\n      <th>sp_defense</th>\n      <th>speed</th>\n      <th>capture_rt</th>\n      <th>gen</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>362</th>\n      <td>40</td>\n      <td>50</td>\n      <td>55</td>\n      <td>50</td>\n      <td>25</td>\n      <td>255</td>\n      <td>3</td>\n    </tr>\n    <tr>\n      <th>132</th>\n      <td>55</td>\n      <td>50</td>\n      <td>45</td>\n      <td>65</td>\n      <td>55</td>\n      <td>45</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>704</th>\n      <td>75</td>\n      <td>53</td>\n      <td>83</td>\n      <td>113</td>\n      <td>60</td>\n      <td>45</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>30</td>\n      <td>35</td>\n      <td>20</td>\n      <td>20</td>\n      <td>45</td>\n      <td>255</td>\n      <td>1</td>\n    </tr>\n    <tr>\n      <th>687</th>\n      <td>52</td>\n      <td>67</td>\n      <td>39</td>\n      <td>56</td>\n      <td>50</td>\n      <td>120</td>\n      <td>6</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{.notes}\nLet's find the nearest neighbours in our Pokémon dataset. \n:::\n\n---\n\n::: {#0d16d005 .cell execution_count=19}\n``` {.python .cell-code}\ndists = euclidean_distances(X_train[:3])\ndists\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```\narray([[  0.        , 213.4338305 , 226.54138695],\n       [213.4338305 ,   0.        ,  64.86139067],\n       [226.54138695,  64.86139067,   0.        ]])\n```\n:::\n:::\n\n\n<br>\n\n::: {#e3571125 .cell execution_count=20}\n``` {.python .cell-code}\ndists[0,2]\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\nnp.float64(226.54138694728607)\n```\n:::\n:::\n\n\n<br>\n\n::: {#f12fe658 .cell execution_count=21}\n``` {.python .cell-code}\nnn = NearestNeighbors(n_neighbors=1)\nnn.fit(X_train);\nnn.kneighbors(X_test.iloc[[1]])\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\n(array([[15.5241747]]), array([[143]]))\n```\n:::\n:::\n\n\n<br>\n\n::: {#a3a90dc8 .cell execution_count=22}\n``` {.python .cell-code}\nX_test.to_numpy().shape\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\n(161, 7)\n```\n:::\n:::\n\n\n:::{.notes}\nThe distance between Pokémon zero and Pokémon 2 can be found using the indexing of `dists[0,2]`.\n\nWe can find the most similar Pokemon from our training data to Pokemon 1 from the test set using the `NearestNeighbors` function from the Sklearn library. \n:::\n\n---\n\n::: {#1d6c9980 .cell execution_count=23}\n``` {.python .cell-code}\nnn = NearestNeighbors(n_neighbors=5)\nnn.fit(X_train);\nnn.kneighbors(X_test.iloc[1])\n```\n:::\n\n\n```out\nValueError: Expected 2D array, got 1D array instead:\narray=[605  55  55  85  55  30 255 335   5].\nReshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.\n```\n<br>\n\n::: {#22880b9c .cell execution_count=24}\n``` {.python .cell-code}\nX_test.iloc[1].shape\n```\n\n::: {.cell-output .cell-output-display execution_count=23}\n```\n(7,)\n```\n:::\n:::\n\n\n::: {#8482cb97 .cell execution_count=25}\n``` {.python .cell-code}\nX_test.iloc[[1]].shape\n```\n\n::: {.cell-output .cell-output-display execution_count=24}\n```\n(1, 7)\n```\n:::\n:::\n\n\n<br>\n\n::: {#489dfc73 .cell execution_count=26}\n``` {.python .cell-code}\nnn = NearestNeighbors(n_neighbors=5)\nnn.fit(X_train);\nnn.kneighbors(X_test.iloc[[1]])\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```\n(array([[15.5241747 , 25.90366769, 27.91057147, 33.3166625 , 34.69870315]]),\n array([[143, 364, 515, 638,   0]]))\n```\n:::\n:::\n\n\n:::{.notes} \nNow let’s find the 5 most similar Pokémon from the training data to our test Pokémon. \n\nWe need to be careful here though because we need to make sure we pass in a 2D NumPy array as an input.\n\nWe can see the top 5 most similar Pokémon to our test example. \n:::\n\n\n# Let’s apply what we learned!\n\n",
    "supporting": [
      "module4_09_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}