{
  "hash": "7e307fbd84aeb350d0203cf823ef107c",
  "result": {
    "engine": "jupyter",
    "markdown": "---\nformat: revealjs\ntitle: The Importance of Preprocessing\ntitle-slide-attributes:\n  data-notes: |\n---\n\n\n\n### So far ...\n \n- Models: Decision trees, 𝑘-NNs, SVMs with RBF kernel.\n- Fundamentals: Train-validation-test split, cross-validation, the fundamental tradeoff, the golden rule.\n \n<br>\n<br>\n \n### Now ...\n \n**Preprocessing**: Transforming input data into a format a machine learning model can use and understand.\n \n \n\n:::{.notes}\nSo far we have seen:   \n \n- Three ML models (decision trees, 𝑘-NNs, SVMs with RBF kernel)\n- ML fundamentals (train-validation-test split, cross-validation, the fundamental trade-off, the golden rule)\n \nAre we ready to do machine learning on real-world datasets?\n\nVery often real-world datasets need to be transformed or ***preprocessed*** before we use them to build ML models.\n:::\n\n---\n \n## Basketball dataset\n\n\n::: {#f59a9a59 .cell execution_count=3}\n``` {.python .cell-code}\nbball_df = pd.read_csv('data/bball.csv')\nbball_df.head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>full_name</th>\n      <th>rating</th>\n      <th>jersey</th>\n      <th>...</th>\n      <th>draft_round</th>\n      <th>draft_peak</th>\n      <th>college</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>LeBron James</td>\n      <td>97</td>\n      <td>#23</td>\n      <td>...</td>\n      <td>1</td>\n      <td>1</td>\n      <td>NaN</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>Kawhi Leonard</td>\n      <td>97</td>\n      <td>#2</td>\n      <td>...</td>\n      <td>1</td>\n      <td>15</td>\n      <td>San Diego State</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>Giannis Antetokounmpo</td>\n      <td>96</td>\n      <td>#34</td>\n      <td>...</td>\n      <td>1</td>\n      <td>15</td>\n      <td>NaN</td>\n    </tr>\n  </tbody>\n</table>\n<p>3 rows × 14 columns</p>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n::: {#2389aad4 .cell execution_count=4}\n``` {.python .cell-code}\nbball_df = bball_df[(bball_df['position'] =='G') | (bball_df['position'] =='F')]\nX = bball_df[['weight', 'height', 'salary']]\ny =bball_df[\"position\"]\nX_train, X_test, y_train, y_test =train_test_split(X, y, test_size=0.20, random_state=123)\n```\n:::\n\n\n<br>\n\n::: {#58583866 .cell execution_count=5}\n``` {.python .cell-code}\nX_train.head(3)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>weight</th>\n      <th>height</th>\n      <th>salary</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>152</th>\n      <td>79.4</td>\n      <td>1.88</td>\n      <td>1588231.0</td>\n    </tr>\n    <tr>\n      <th>337</th>\n      <td>82.1</td>\n      <td>1.91</td>\n      <td>2149560.0</td>\n    </tr>\n    <tr>\n      <th>130</th>\n      <td>106.6</td>\n      <td>2.03</td>\n      <td>6500000.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{.notes}\nIn module 3, we used a portion of the basketball dataset to predict a player's position using `DecisionTreeClassifier`.\n \nCan we use a 𝑘-NN classifier for this task?\n \nWe are going to attempt to predict a player’s position (whether a particular player is a point guard ('G') or a forward ('F')).\n\nRight now, we are only going to be using the numeric columns `weight` `height` and `salary` for our `X` object and our column `position` for our `y`. \n\nWe will dive into categorical variables in module 6.\n:::\n\n---\n \n### Dummy Classifier\n\n::: {#bd23c269 .cell execution_count=6}\n``` {.python .cell-code}\nfrom sklearn.dummy import DummyClassifier\nfrom sklearn.model_selection import cross_validate\n\ndummy = DummyClassifier(strategy=\"most_frequent\")\nscores = cross_validate(dummy, X_train, y_train, return_train_score=True)\nprint('Mean validation score', scores['test_score'].mean().round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean validation score 0.57\n```\n:::\n:::\n\n\n<br>\n\n::: {#6f901c67 .cell execution_count=7}\n``` {.python .cell-code}\nfrom sklearn.neighbors import KNeighborsClassifier\n\nknn = KNeighborsClassifier()\nscores = cross_validate(knn, X_train, y_train, return_train_score=True)\nprint('Mean validation score', scores['test_score'].mean().round(2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nMean validation score 0.5\n```\n:::\n:::\n\n\n:::{.notes}\nFirst, let's see what scores we get if we simply predict the most occurring position in the dataset using our dummy classifier.\n\nWe get a score of 0.57. \nNow if we build our 𝑘-NN classifier we determine that it gets an even *worse* score of 0.50! \n\nDummy classifiers are supposed to be a baseline and so why is it getting a better score than a model that is actually doing machine learning? What’s going on?\n:::\n\n---\n\n::: {#b32902ae .cell execution_count=8}\n``` {.python .cell-code}\ntwo_players = X_train.sample(2, random_state=42)\ntwo_players\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>weight</th>\n      <th>height</th>\n      <th>salary</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>285</th>\n      <td>91.2</td>\n      <td>1.98</td>\n      <td>1882867.0</td>\n    </tr>\n    <tr>\n      <th>236</th>\n      <td>112.0</td>\n      <td>2.08</td>\n      <td>2000000.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n::: {#bb9fa445 .cell execution_count=9}\n``` {.python .cell-code}\nfrom sklearn.metrics.pairwise import euclidean_distances\neuclidean_distances(two_players)[1,0]\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\nnp.float64(117133.00184682972)\n```\n:::\n:::\n\n\n<br>\n\n::: {#84c2b925 .cell execution_count=10}\n``` {.python .cell-code}\ntwo_players_subset = two_players[[\"salary\"]]\ntwo_players_subset\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>salary</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>285</th>\n      <td>1882867.0</td>\n    </tr>\n    <tr>\n      <th>236</th>\n      <td>2000000.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n<br>\n\n::: {#48118a54 .cell execution_count=11}\n``` {.python .cell-code}\neuclidean_distances(two_players_subset)[1,0]\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\nnp.float64(117133.0)\n```\n:::\n:::\n\n\n:::{.notes}\nLet's have a look at just 2 players. \n\nWe can see the values in each column. \n\nThe values in the `weight` column are around 100, and the values in the `height` column are around 2. \n\nThe salary column has values much higher at around 2 million. \n\nLet’s now calculate the distance between the two players.\n \nWe can see the distance between player 285 and 236 is 117133.00184683.\n \nWhat happens if we only consider the `salary` column though?\n \nIt looks like we get almost the same distance!\n \nThe distance is completely dominated by the feature with larger values.\n \nThe features with smaller values are being ignored.\n \nDoes it matter?\n \n- Yes! The scale is based on how data was collected.\n- Features on a smaller scale can be highly informative and there is no good reason to ignore them.\n- We want our model to be robust and not sensitive to the scale.\n \nWas this a problem for decision trees?\n \n- No. In decision trees we ask questions on one feature at a time.\n  \nSo, what do we do about this?\n \nWell, we have to scale the columns so they are all using a similar range of values!\n \nLuckily Sklearn has tools called ***transformers*** for this.\n:::\n\n---\n \n## Transformers: Scaling example\n\n::: {#b52a794e .cell execution_count=12}\n``` {.python .cell-code}\nfrom sklearn.preprocessing import StandardScaler\n\nscaler = StandardScaler()\t# Create feature transformer object\nscaler.fit(X_train); # Fitting the transformer on the train split\nX_train_scaled = scaler.transform(X_train) # Transforming the train split\nX_test_scaled = scaler.transform(X_test) # Transforming the test split\npd.DataFrame(X_train_scaled, columns = X_train.columns).head()\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>weight</th>\n      <th>height</th>\n      <th>salary</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>-1.552775</td>\n      <td>-1.236056</td>\n      <td>-0.728809</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>-1.257147</td>\n      <td>-0.800950</td>\n      <td>-0.670086</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1.425407</td>\n      <td>0.939473</td>\n      <td>-0.214967</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1.370661</td>\n      <td>1.664650</td>\n      <td>-0.585185</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>0.286690</td>\n      <td>-0.510879</td>\n      <td>-0.386408</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::{.notes}\nOne form of preprocessing we can do is ***scaling*** we will talk about this in more detail to come but for now just take a look at the tools we are using.\n \nWe'll be using `sklearn`'s [`StandardScaler`](https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.StandardScaler.html), which is a `transformer`. \n \n For now, try to only focus on the syntax.\n \n We'll talk about scaling in a bit.\n \n1. Create a feature transformer object. This is done in a similar way to how we create a model. Transformers accepts hyperparameters as well.\n2. Fitting the transformer on the train split.\n3. Transform the train split using `.transform()`.\n4. Then transform the test split.\n \n`sklearn` uses `fit` and `transform` paradigms for feature transformations. (In model building it was `fit` and `predict` or `score`)\n\nWe `fit` the transformer on the train split and then `transform` the train split as well as the test split.\n\n`transform` replaces `predict` here. \n\nWe can now see that our values in our `X_train` have been scales so they are now all on the same scale. \n\nThe `salary` values are no longer greater than the values in the `height` and `weight` columns. \n:::\n\n---\n \n## Sklearn's *predict* vs *transform*\n \n```python\nmodel.fit(X_train, y_train)\nX_train_predictions = model.predict(X_train)\n```\n \n <br>\n\n```python\ntransformer.fit(X_train, [y_train])\nX_train_transformed = transformer.transform(X_train)\n```\n\nor \n\n```python\nX_train_transformed = transformer.fit_transform(X_train)\n```\n\n \n:::{.notes}\nLet’s solidify this new concept of `transform`.\n\nSuppose we have a named `model` which is either a classification or regression model.\n \nWe can compare `predict` with `transformer` which is a transformer used to change the input representation to scale numeric features.\n\nWe do similar steps by calling `fit` first, followed by `transform` on our training data just like we did `fit` and then `predict` in classification and regression. \n \nWe can pass `y_train` in `fit` but it's usually ignored. It allows us to pass it just to be consistent with the usual usage of `sklearn`'s `fit` method.  \n \nWe can also carry out fitting and transforming in one call using `.fit_transform()`, but we must be mindful to use it only on the train split and **not** on the test split.\n:::\n\n---\n\n::: {#7253d81b .cell execution_count=13}\n``` {.python .cell-code}\nknn_unscaled = KNeighborsClassifier()\nknn_unscaled.fit(X_train, y_train);\nprint('Train score: ', (round(knn_unscaled.score(X_train, y_train), 2)))\nprint('Test score: ', (round(knn_unscaled.score(X_test, y_test), 2)))\n```\n:::\n\n\n```out\nTrain score:  0.71\nTest score:  0.45\n```\n\n<br>\n\n::: {#6dc777ce .cell execution_count=14}\n``` {.python .cell-code}\nknn_scaled = KNeighborsClassifier()\nknn_scaled.fit(X_train_scaled, y_train);\nprint('Train score: ', (round(knn_scaled.score(X_train_scaled, y_train), 2)))\nprint('Test score: ', (round(knn_scaled.score(X_test_scaled, y_test), 2)))\n```\n:::\n\n\n```out\nTrain score:  0.94\nTest score:  0.89\n```\n \n:::{.notes}\nLet's check whether scaling makes any difference for 𝑘-NNs.\n \nThe scores with scaled data are now much better compared to the unscaled data in the case of 𝑘-NNs.\n\nWe can see now that 𝑘-NN is doing better than the Dummy Classifier when we scaled our features. \n \nWe are not carrying out cross-validation here for a reason that we'll look into soon.\n \nWe are being a bit sloppy here by using the test set several times for teaching purposes.\n \nBut when we build any ML models, we should only assess the test set once. \n:::\n \n\n# Let’s apply what we learned!\n\n",
    "supporting": [
      "module5_01_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}